### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ImInTheICU** [LingBlackSama/LB-Connection#1]
How you out here building a custom remote framework but having obvious errors in ur code.
![image](https://user-images.githubusercontent.com/111275373/222893884-5d399ba7-c7c2-4d9e-9e06-bb04dcd87661.png)
(quick-install script)

**Comment by VioletGrace0622** [comment]
The issue occurred because the code was executed within a `script` instead of a command line. As a result, the `script` did not have sufficient permissions to utilize `game:GetService("HttpService").HttpEnabled = true`

**Comment by VioletGrace0622** [comment]
**Command Bar instead of Script**
![image](https://user-images.githubusercontent.com/88409650/222930626-6d23b533-b6ba-420c-879c-f0e2e5a26dbe.png)
